name: 'Storage Optimize'
description: 'Free up disk space on GitHub Actions runner'
runs:
  using: "composite"
  steps:
    - name: Cleanup
      shell: bash
      run: |
        sudo rm -rf \
          /usr/lib/jvm \
          /usr/share/dotnet \
          /usr/share/swift \
          /usr/local/.ghcup \
          /usr/local/julia* \
          /usr/local/lib/android \
          /usr/local/share/chromium \
          /opt/microsoft /opt/google \
          /opt/az \
          /usr/local/share/powershell \
          /opt/hostedtoolcache &
        docker system prune -af || true &
        docker builder prune -af || true &
        wait
        df -h
