
name: "Terramate and OpenTofu Setup and Cache"
description: "Setup Terramate and OpenTofu"
inputs:
  opentofu_version:
    description: "OpenTofu version to install"
    required: false
    default: "1.10.0"
  terramate_version:
    description: "Terramate version to install"
    required: false
    default: "0.14.7"
runs:
  using: "composite"
  steps:
    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@847eaa4afeb791b06daa46e8eafa8b1b68d7cfb4  # v2.0.1
      with:
        tofu_version: ${{ env.OPENTOFU_VERSION }}
        tofu_wrapper: false

    - name: Setup Terramate
      uses: terramate-io/terramate-action@c5a1375801a3fac44d29fc7e0ebb3757ea0db3e0  # v3.0.0
      with:
        version: ${{ env.TERRAMATE_VERSION }}

    - name: Check Terramate configurations are up to date
      shell: bash
      run: |
        terramate generate
        if ! git diff --quiet; then
          echo "Error: Terramate generated files are not up to date!"
          echo "Please run 'terramate generate' locally and commit the changes."
          git diff
          exit 1
        fi
        echo "Terramate generated files are up to date."

    - name: Tofu init changed stacks
      shell: bash
      run: terramate run --changed tofu init

    - name: List changed stacks
      shell: bash
      run: terramate list --changed

