name: Secrets Scan Workflow
on:
  push:
    branches:
      - detect-secrets
  pull_request:
    branches:
      - detect-secrets

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: ./.github/actions/detect-secrets
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gitleaks_license: ${{ secrets.GITLEAKS_LICENSE }}