name: Secrets Scan Workflow
on:
  push:
    branches:
      - detect-secrets
  pull_request:
    branches:
      - detect-secrets

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/detect-secrets/action.yaml@detect-secrets